### ISSUE TITLE
Is `Showdown` or `showdown` ?

### ISSUE THREAD

**Issue by pizn** [showdownjs/table-extension#3]
Hello.

The namespace need be `showdown` not `Showdown`. [The code here.](https://github.com/showdownjs/table-extension/blob/master/src/table.js#L103)

What difference of that? What to consider when you modify the namespace?

**Comment by tivie** [comment]
> The namespace need be showdown not Showdown. The code here.

In the current "stable" version, the namespace is `Showdown`.  ([see here](https://github.com/showdownjs/showdown/blob/31d62380cd65b06982f8f75d6768c8f18d736c6b/src/showdown.js#L67))

In the 1.0.0-alpha.1 the namespace was changed to `showdown`.
The table extensions will be updated accordingly when we release showdown core library 1.0.0 stable.

> What difference of that? What to consider when you modify the namespace?

Not much, just consistency with most of javascript conventions and with the lint tool we use for build. Usually javascript programmers expect camelCase for regular identifiers (including namespaces), CAPSLOCK for "constants" and ProperCase for object constructors (indicating they should always be invoked using new).

So, in V1.0.0 `Showdown.converter()` becomes `showdown.Converter()`

**Comment by pizn** [comment]
Nice,  thank you :D
