### ISSUE TITLE
current version Not compatible with showdown last-release

### ISSUE THREAD

**Issue by xixilive** [showdownjs/table-extension#4]
```
window.showdown //lowercase
```

is defined in showdown latest-releases, 
but table-ext require a 

```
window.Showdown //camelcase
```

object in current version.

**Comment by tivie** [comment]
We're still updating extensions. We will fix this as soon as possible

**Comment by tivie** [comment]
@xixilive Ok! This should be fixed in https://github.com/showdownjs/table-extension/releases/tag/1.0.0

**Comment by xixilive** [comment]
GOOD JOB!

**Comment by xixilive** [comment]
GOOD JOB!
